In [20]:
import numpy as np

N_COL = 50
N_ROW = 50
N_EGENT = N_COL * N_ROW  # エージェント数

N_STEP = 1000  # ステップ数

# 係数を1で初期化
C1 = np.array([1]*N_EGENT)
C2 = np.array([1]*N_EGENT)
C3 = np.array([1]*N_EGENT)

# 各エージェントの模倣傾向度を正規分布で初期化
k = np.random.randn(N_EGENT, N_EGENT)
k_t = [k]

# 各エージェントの投資判断を-1か1でランダムに初期化
s = np.array(list(map(lambda x: 1 if x < 0 else -1, np.random.randn(N_EGENT)))).reshape(N_ROW, N_COL)
s_t = [s]

# 各エージェントのニュースへの信頼度を正規分布で初期化
u = np.random.randn(N_EGENT, N_EGENT)
u_t = [u]

# ニュースを正規分布で初期化
news = np.random.randn()
news_t = [news]

# 自身が持つ情報
eps = np.random.randn(N_EGENT, N_EGENT)
eps_t = [k]

# 各エージェントが持つ現金を1で初期化
cash = np.array([1]*N_EGENT)
cash_t = [cash]

# 各エージェントが持つ株式数を1で初期化
stock = np.array([1]*N_EGENT)
stock_t = [stock]

# 株価を1で初期化
price = 1
price_t = [price]

# 各定数パラメータ
LAMBDA = 0.25
OPINION_TH_MAX = 2.0
G = 0.02
ALPHA = 0.95

opinion = [[] for _ in range(N_EGENT)]

# 各時間での値を計算
for step in N_STEP:
    # 各エージェントに対する計算
    for row in range(N_ROW):
        for col in range(in N_COL):
            e_i = row*N_COL + col  # エージェントの番号
            
            # opinionの計算
            # 右辺第一項の計算
            ke_sum = 0
            try:
                e_j = (row-1)*N_COL + col
                ke_sum += k_t[:-1][e_i, e_j] * s_t[:-1][e_i, e_]
            opi += C1[e_i] * sum()
            
        


[[ 1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1  1 -1]
 [ 1  1  1 ...  1  1  1]
 ...
 [ 1 -1 -1 ... -1  1  1]
 [-1 -1 -1 ...  1  1 -1]
 [-1  1 -1 ... -1  1 -1]]
